version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: prontuario-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: prontuario_digital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: prontuario-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  postgres_data:
