# Review Apps por PR (compose profiles)
# Uso:
#   PR_NUMBER=123 API_PORT=33030 WEB_PORT=35173 pnpm run review:up
#   PR_NUMBER=123 pnpm run review:down
name: prontuariodigital
services:
  db:
    image: postgres:16-alpine
    container_name: prontuario-db-review-${PR_NUMBER:-local}
    profiles: ["review"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prontuario_digital
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prontuario_digital"]
      interval: 3s
      timeout: 3s
      retries: 50
    volumes:
      - review_postgres_data_${PR_NUMBER:-local}:/var/lib/postgresql/data

  api:
    image: node:22-alpine
    container_name: prontuario-api-review-${PR_NUMBER:-local}
    profiles: ["review"]
    working_dir: /app
    environment:
      NODE_ENV: production
      PORT: "3030"
      HOST: "0.0.0.0"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/prontuario_digital"
    command: >
      sh -lc "
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        pnpm i --frozen-lockfile &&
        pnpm run prisma:generate &&
        node ./server/server-pro.cjs
      "
    ports:
      - "${API_PORT:-3030}:3030"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app:ro

  web:
    image: node:22-alpine
    container_name: prontuario-web-review-${PR_NUMBER:-local}
    profiles: ["review"]
    working_dir: /app
    environment:
      NODE_ENV: production
    command: >
      sh -lc "
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        pnpm --dir webapp i --frozen-lockfile &&
        pnpm --dir webapp run build &&
        pnpm --dir webapp run preview -- --host 0.0.0.0 --port ${WEB_PORT:-5173}
      "
    ports:
      - "${WEB_PORT:-5173}:${WEB_PORT:-5173}"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./:/app:ro

volumes:
  review_postgres_data_${PR_NUMBER:-local}:
